vesc_driver_node:
  ros__parameters:
    port: "/dev/vesc"         # falls back to /dev/ttyACM0 if symlink not present
    duty_cycle_min: -0.10
    duty_cycle_max:  0.10
    current_min:    -50.0
    current_max:     50.0
    speed_min:    -20000
    speed_max:     20000
